routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/',                                 'HomeController@index')         ->name('home');

Route::get('/carrinho-de-compras',              'CartController@index')         ->middleware('auth')->name('cart');
Route::post('/adicionar-ao-carrinho/{name?}',   'CartController@add')           ->name('cart.add');
Route::post('/remover-do-carrinho/{id?}',       'CartController@remove')        ->name('cart.remove');
Route::post('/comprar/{name?}',                 'ProductController@buy')        ->name('product.buy');

Route::post('/finalizar-compra',                'CartController@order')         ->name('cart.order');

Route::get('/categoria/{id?}/{name?}',          'CategoryController@index')     ->name('product.category');
Route::get('/produto/image/{filename?}',        'ProductController@image')      ->name('product.image');
Route::post('/busca',                           'ProductController@search')     ->name('product.search');
Route::get('/{id}/{name}',                      'ProductController@index')      ->name('product');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;
use App\Providers\HelperServiceProvider as Helper;

class Item extends Model
{
    protected $fillable =
    [
        'price',
        'product_id'
    ];

    protected $hidden = 
    [
        'created_at', 'updated_at',
    ];

    public function cart()
    {
        return $this->belongsTo('App\Cart');
    }

    public function product()
    {
        return $this->belongsTo('App\Product');
    }

    public function getPriceFormatedAttribute()
    {
        return Helper::getFormatMoney($this->price);
    }
}

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('partials.search') 

    <div class="row">

        <div class="col-12">

            @if (session('message'))
                <div class="alert alert-success">
                    {{ session('message') }}
                </div>
            @endif

            <div class="row">

            @if( Session::has("searchTerm") )
                <div class="col-12">
                    <div class="alert alert-success">
                        <p class="m-0 p-0">Resultados encontrados para: {{ Session::get("searchTerm") }}</p>
                    </div>
                </div>
            @endif
            
           
                <div class="col-12">
                    
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col"></th>
                            <th scope="col">Produto</th>
                            <th scope="col"></th>
                            <th scope="col">Valor</th>
                            <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($carts as $cart)
                                @foreach ($cart->items as $item)
                                <tr>
                                    <th scope="row">{{$item->id}}</th>
                                    <td>
                                        <a href="{!! route('product', [$item->product->id, str_slug($item->product->name)]) !!}">
                                            <img class="card-img-top" style="width: 30px;" src="{!! route('product.image', [$item->product->image]) !!}" alt="{{$item->product->name}}">
                                        </a>
                                    </td>
                                    <td>{{$item->product->name}}</td>
                                    <td class="text-center"></td>
                                    <td>{{$item->price_formated}}</td>
                                    <td class="text-right">
                                        <form action="{!! route('cart.remove', [str_slug($item->product->name)]) !!}" method="POST">
                                            @csrf
                                            <input type="hidden" name="item_id" value="{{$item->id}}">
                                            <input type="hidden" name="cart_id" value="{{$cart->id}}">
                                            <button type="submit" onclick="submit();" class="btn btn-danger mr-0 mb-0" title="Remover do carrinho de compras"><i class="far fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">Total:</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </tfoot>
                    </table>

                </div>

                <div class="col-12 my-3">
                    <form action="{!! route('cart.order') !!}" method="POST">
                        @csrf
                        <input type="hidden" name="cart_id" value="{{$cart->id}}">
                        <button type="submit" onclick="submit();" class="btn btn-success btn-lg btn-block" title="Finalizar Compra"><i class="fas fa-credit-card"></i> Finalizar Compra</button>
                    </form>
                </div>
            
            </div>
        </div>

    
    </div>

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('partials.search') 

    <div class="row">

        <div class="col-3 d-none d-md-block">
            <h3>Categorias</h3>
            <ul class="nav nav-pills nav-fill flex-column">
                @foreach ($categories as $category)
                <li class="nav-item text-left">
                    <a class="nav-link {!! isset($current_category) && $current_category == $category->id ? 'active' : '' !!}" href="{!! route('product.category', [$category->id, str_slug($category->name)]) !!}">
                        {{$category->name}}
                    </a>
                </li>
                @endforeach
            </ul>
        </div>

        <div class="col-12 col-md-9">

            @if (session('message'))
                <div class="alert alert-success">
                    {{ session('message') }}
                </div>
            @endif

            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif

            <div class="row">

            @if( Session::has("searchTerm") )
                <div class="col-12">
                    <div class="alert alert-success">
                        <p class="m-0 p-0">Resultados encontrados para: {{ Session::get("searchTerm") }}</p>
                    </div>
                </div>
            @endif
            
            @foreach ($products as $product)
                <div class="col-12 col-md-6 col-lg-4 mb-4">
                    @include('partials.product-card') 
                </div>
            @endforeach
            
            </div>
        </div>

    
    </div>

    <!-- <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div> -->

</div>
@endsection

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('partials.search')

    <div class="row">
    @if (isset($product))

        @if (session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif

        @if (session('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
        @endif

        <div class="col-12">
            <h1>{{$product->name}}</h1>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card align-self-stretch">
                <img class="card-img-top" src="{!! route('product.image', [$product->image]) !!}" alt="Card image cap">
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-8 mb-4">
                
                    <div>
                    <h5>
                        {{$product->price_formated}}
                    </h5>
                    @foreach ($product->categories as $category)
                        <span class="badge badge-info">{{$category->name}}</span>
                    @endforeach
                    </div>
                    <p class="card-text">{{$product->description}}</p>
                    <form action="{!! route('product.buy', [str_slug($product->name)]) !!}" method="POST">
                        @csrf
                        <input type="hidden" name="product_id" value="{{$product->id}}">
                        <button type="submit" onclick="submit();" class="btn btn-success mr-2 mb-2" title="Comprar">Comprar</button>
                    </form>
                    <form action="{!! route('cart.add', [str_slug($product->name)]) !!}" method="POST">
                        @csrf
                        <input type="hidden" name="product_id" value="{{$product->id}}">
                        <button type="submit" onclick="submit();" class="btn btn-primary mr-2 mb-2" title="Adicionar ao carrinho de compras"><i class="fas fa-cart-arrow-down"></i></button>
                    </form>

        </div>
    @endif
    </div>

</div>
@endsection